model_name_or_path : distilbert-base-uncased
experiment_location : /Users/puneet.jain@databricks.com/ner_bio
run_name: ner_bionlp_2004
task_name: ner

log_level: debug

do_train: true
do_eval: true

dataset_name: tner/bionlp2004

# database_name: default
# train_table: banking77_train
# validation_table: banking77_test


feature_col: tokens
label_col: tags
label_all_tokens: true


max_seq_length: 512
learning_rate: 0.00003
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
evaluation_strategy: epoch
save_strategy: epoch
load_best_model_at_end: true
metric_for_best_model: seqeval
num_train_epochs: 10
seed: 123
output_dir: tmp/distilbert-base-uncased