model_name_or_path : albert-base-v2
experiment_location : /Shared/transformer_experiments/classification_experiments
run_name: banking_test_run
log_level: debug

do_train: true
do_eval: true

database_name: default
train_table: banking77_train
validation_table: banking77_test

logging.get_log_levels_dict(): banking77

feature_col: text
label_col: label
num_labels: 77


max_token_length: 40
max_seq_length: 256
learning_rate: "1e-4"
per_device_train_batch_size: 128
per_device_eval_batch_size: 128
evaluation_strategy: epoch
save_strategy: epoch
load_best_model_at_end: true
metric_for_best_model: "accuracy"
num_train_epochs: 2
save_total_limit: 10
seed: 123
output_dir: tmp/albert