model_name_or_path : xlm-roberta-large
run_name: xlm-roberta-large
task_name: multi-class

log_level: debug

do_train: true
do_eval: true

# dataset_name: banking77

database_name: default
train_table: banking77_train
validation_table: banking77_test


feature_col: text
label_col: label

max_train_samples: 1000
max_eval_samples: 10
max_seq_length: 256
learning_rate: 0.000004
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
evaluation_strategy: epoch
save_strategy: epoch
load_best_model_at_end: true

metric_for_best_model: accuracy
evaluate_metric: seqeval

num_train_epochs: 1
max_steps: 1

seed: 123
#todo: get the root path from outside/env variable
output_dir: /dbfs/udhayaraj.sivalingam@databricks.com/transformers/xlm-roberta-base
